version: '3.7'
volumes:
  certbot-etc:
  certbot-var:
  nginx-config:

services:

  site:
    build: .
    restart: always
    container_name: site
    ports:
      - 9000:8080

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - site
